version: "3.8"
services:
  wandb:
    image: wandb/local
    container_name: TRUEADC-AI-wandb-local
    ports:
      - "8081:8080"
    networks:
      - TRUEADC-AI-network

  main:
    build:
      context: .
    container_name: TRUEADC-AI-main
    depends_on:
      - wandb
    environment:
      - WANDB_BASE_URL=http://wandb:8080
    command: >
      bash -c "echo 'Access W&B at http://localhost:8081' && bash"
    stdin_open: true
    tty: true
    #volumes: Specify volumes for mounting

    networks:
      - TRUEADC-AI-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '4gb' #Shared memory
networks:
  TRUEADC-AI-network:
    name: TRUEADC-AI-network


#docker compose up -d #be in same directory as yaml file
#Then enter the container interactively:
#docker exec -it MRIdenoise-main bash
#Also login to wandb by running in container CLI:
#wandb login
#Create an account and paste you API key to the CLI.


